// Watch Party client.
//
// Design: docs/plans/2026-08-21-watch-party-design.md
//
// The host is authoritative and viewers reconcile. Crucially, every viewer
// resolves its OWN signed stream URL rather than receiving the host's: Pluto
// JWTs are per-session and expire in 24h, so a shared URL would break for
// everyone at once. Only playback POSITION travels between peers.

import { getSupabase } from "./auth";
import { getActiveProfile } from "./profiles";
import { allowedRatingsFor } from "./db";
import { showToast } from "./util";
import { openVodPlayer, setPartyEmitter, applyPartyState, setPartyViewerMode, resyncToHost, stopPartySync, type PartyPlaybackState } from "./vodplayer";

const WORKER_URL = (import.meta.env.VITE_PARTY_WORKER_URL as string) || "";

let socket: WebSocket | null = null;
let currentCode: string | null = null;

function code6(): string {
  const A = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no O/0, I/1 — read aloud safely
  return Array.from({ length: 6 }, () => A[Math.floor(Math.random() * A.length)]).join("");
}

// The party a guest is currently in, remembered across a reload or an
// accidental close. Without this, someone who shut the tab had to go and find
// the original invite message again to get back into a party still running --
// and the code is not shown anywhere once the player is open.
const LAST_PARTY_KEY = "veedeeoh_last_party";

export interface LastParty { code: string; title: string; at: number; role: "host" | "guest" }

export function rememberParty(code: string, title: string, role: "host" | "guest" = "guest"): void {
  try { localStorage.setItem(LAST_PARTY_KEY, JSON.stringify({ code, title, role, at: Date.now() })); } catch {}
}

export function forgetParty(): void {
  try { localStorage.removeItem(LAST_PARTY_KEY); } catch {}
}

/** The last party joined, if it is recent enough to still plausibly be running.
 *  Six hours is well past any film, and stale enough entries are dropped rather
 *  than offered as a rejoin that will fail. */
export function recentParty(): LastParty | null {
  try {
    const raw = localStorage.getItem(LAST_PARTY_KEY);
    if (!raw) return null;
    const p = JSON.parse(raw) as LastParty;
    if (!p?.code || Date.now() - (p.at || 0) > 6 * 3600_000) { forgetParty(); return null; }
    return { ...p, role: p.role === "host" ? "host" : "guest" };
  } catch { return null; }
}

export function partyLink(joinCode: string): string {
  return `${location.origin}/index.html?party=${joinCode}`;
}

// ---------------------------------------------------------------- hosting ---

/** Hosting is an ACCOUNT-level entitlement: only the account owner starts a
 *  party, never a kids profile, and never a lapsed account.
 *
 *  The subscription check is the real anti-abuse control for the free tier. A
 *  lapsed guest may ATTEND a party, so they can only ever watch what a paying
 *  customer chose to play; letting them host would hand them the whole catalogue
 *  back and make the paywall decorative. Credits, when they arrive, are a
 *  quantity on top of this gate -- not a substitute for it.
 *
 *  Enforced again by RLS, because a hidden button is not a control.
 */
export async function canHost(): Promise<boolean> {
  if (getActiveProfile()?.is_kids) return false;
  const { data } = await getSupabase().auth.getUser();
  if (!data.user) return false;
  const { hasActiveAccess } = await import("./db");
  // Fail CLOSED here, unlike the browse gate. A transient error that wrongly
  // lets someone browse is a small mistake; one that lets a lapsed account host
  // is the hole this exists to close.
  try { return await hasActiveAccess(); } catch { return false; }
}

export interface PartyOptions {
  contentId: string;
  streamIdx: number;
  title: string;
  seatLimit?: number | null;
  requireApproval?: boolean;
  isPublic?: boolean;
  blurb?: string | null;
}

/** 256 bits of randomness, generated by the host and never sent to a guest.
 *  This is what proves host identity to the Durable Object; the join code alone
 *  used to be enough, which meant anyone with the link could take the controls. */
function hostToken(): string {
  const b = new Uint8Array(32);
  crypto.getRandomValues(b);
  return Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");
}

// localStorage, not sessionStorage. This is the ONLY thing that proves a
// connection is the host's, so keeping it per-tab meant closing the tab
// permanently forfeited control of a party that is still running -- the host
// could not even rejoin their own room.
const tokenKey = (joinCode: string) => `veedeeoh_party_host_${joinCode}`;

function saveHostToken(joinCode: string, token: string): void {
  try { localStorage.setItem(tokenKey(joinCode), token); } catch {}
}
function readHostToken(joinCode: string): string | null {
  try { return localStorage.getItem(tokenKey(joinCode)); } catch { return null; }
}

export async function createParty(opts: PartyOptions): Promise<{ joinCode: string; link: string; partyId: string }> {
  const { data: u } = await getSupabase().auth.getUser();
  if (!u.user) throw new Error("not signed in");
  if (!WORKER_URL) throw new Error("Watch Party isn't configured yet");

  const joinCode = code6();
  const token = hostToken();

  const { data: created, error } = await getSupabase().from("parties").insert({
    host_user_id: u.user.id,
    join_code: joinCode,
    content_id: opts.contentId,
    stream_idx: opts.streamIdx,
    title: opts.title,
    seat_limit: opts.seatLimit ?? null,
    is_public: !!opts.isPublic,
    blurb: opts.isPublic ? (opts.blurb || null) : null,
    // Snapshotted so the listing has a name without exposing the host's
    // profile row, and so a later rename does not retitle a past party.
    host_name: opts.isPublic ? (getActiveProfile()?.name || null) : null,
  }).select("id").single();
  if (error) throw error;

  // Bind the party to this host BEFORE the link exists. Init is one-shot, so
  // there is no window in which someone who guessed the code could claim it.
  const res = await fetch(`${WORKER_URL}/init?party=${joinCode}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      hostToken: token,
      hostUserId: u.user.id,
      seatLimit: opts.seatLimit ?? null,
      requireApproval: opts.requireApproval !== false,
    }),
  });
  if (!res.ok) throw new Error("Couldn't start the party channel");

  saveHostToken(joinCode, token);
  partyTitle = opts.title;
  partyRowId = (created as any)?.id || "";
  partyStartedAt = 0;
  peakViewers = 0;
  rememberParty(joinCode, opts.title, "host");

  return { joinCode, link: partyLink(joinCode), partyId: (created as any)?.id || "" };
}

// ---------------------------------------------------------------- joining ---

export async function joinParty(joinCode: string): Promise<void> {
  if (!WORKER_URL) { showToast("Watch Party isn't configured yet"); return; }

  // A guest following a link previously landed on Home and waited through the
  // catalogue load, the party lookup and the stream resolve with nothing on
  // screen explaining any of it -- so the invite looked like it had failed
  // right up until the film appeared. Covered, and torn down on every exit
  // path below.
  const veil = showJoining(joinCode);

  const sb = getSupabase();
  // Through the definer function, not a table select. The select policy no
  // longer exposes other people's parties -- it used to expose every open one
  // with its code, so any signed-in user could enumerate and walk into a
  // "private" party. Knowing the code is now the credential.
  const { data: rows, error } = await sb.rpc("party_by_code", { code: joinCode });
  const party = Array.isArray(rows) ? rows[0] : rows;
  if (error || !party) { veil(); showToast("That party has ended or the link is wrong"); return; }

  // THE KIDS TRAP. A party link handed to a kids profile would otherwise play
  // whatever the host is playing. Refuse outright rather than filtering -- a
  // control any Discord link walks around is not a control.
  const profile = getActiveProfile();
  const allowed = allowedRatingsFor(profile);
  if (allowed) {
    const item = await lookupCatalogItem(party.content_id);
    const rating = (item?.rating || "").toUpperCase();
    if (!rating || !allowed.has(rating)) {
      veil();
      showToast(`This party is playing something outside ${profile.name}'s rating limits`);
      return;
    }
  }

  const { data: u } = await sb.auth.getUser();
  if (!u.user) { veil(); showToast("Sign in to join the party"); return; }

  // Two separate records, deliberately. party_joins is the presence log for
  // this party; the referral is a permanent, first-touch claim on the guest's
  // account that outlives it. attribute_party_join is a no-op if the guest
  // already has a referrer, so an existing customer joining a party does not
  // get reassigned to the host.
  await sb.from("party_joins").upsert({
    party_id: party.id, user_id: u.user.id, host_user_id: party.host_user_id,
  }).then(({ error: e }) => { if (e) console.warn("[party] join not recorded", e); });

  await sb.rpc("attribute_party_join", { party: party.id })
    .then(({ error: e }) => { if (e) console.warn("[party] referral not recorded", e); });

  const item = await lookupCatalogItem(party.content_id);
  if (!item) { veil(); showToast("That title isn't in the catalog any more"); return; }

  // Each viewer resolves their OWN url -- a Pluto JWT is per-session and
  // expires, so the host's cannot be shared. asPartyChannel used to read
  // `item.url`, which is only set for legacy catalogue rows, so a Pluto, Tubi
  // or Archive title handed the player a stream with url undefined and the
  // joiner landed on "this title isn't available to stream right now".
  const vod = await import("./vod");

  // A series guest needs the WHOLE episode list, not just one URL. streamIdx is
  // an index into this array, so without it a host moving to episode 4 would
  // send an index the viewer cannot resolve.
  let streams: any[] | null = null;
  if (item.series_id) {
    const { fetchVodSeries } = await import("./api");
    const eps = await fetchVodSeries(item.series_id).catch(() => [] as any[]);
    if (eps.length) {
      streams = [...eps]
        .sort((a, b) => (a.season ?? 1) - (b.season ?? 1) || (a.number ?? 0) - (b.number ?? 0))
        .map((ep) => ({
          url: ep.url, quality: null,
          source: `S${ep.season ?? "?"}E${ep.number ?? "?"} ${ep.title}`.slice(0, 48),
        }));
    }
  }

  const url = streams?.length ? null : await vod.resolveItemStream(item);
  if (!streams?.length && !url) { veil(); showToast("That title can't be streamed right now"); return; }

  // Do NOT open the player yet. A guest was dropped straight into the film the
  // instant they joined, so the host had no moment to gather anyone and an
  // early arrival watched alone. The player opens on the host's start signal --
  // or immediately, if the worker reports the party already running, which is
  // what a late joiner gets.
  partyTitle = item.title || "a watch party";
  partyRowId = party.id;
  partyStartedAt = Date.now();
  rememberParty(joinCode, partyTitle, "guest");

  const { showGuestLobby } = await import("./party-setup");
  const closeLobby = showGuestLobby(item, joinCode);
  veil();

  window.addEventListener("veedeeoh:party-dead", () => closeLobby(), { once: true });

  window.addEventListener("veedeeoh:party-start", () => {
    closeLobby();
    // Viewer mode goes on BEFORE the player mounts. Applying it afterwards left
    // a window where the transport controls were live, and the viewer in
    // testing used exactly that window to press play.
    setPartyViewerMode(true);
    // `streams` carries the whole episode list for a series, which is what
    // makes the host's streamIdx resolvable. An earlier edit to pass it did not
    // apply -- the argument is optional, so nothing failed to compile and the
    // guest silently kept a one-episode list.
    void openVodPlayer(asPartyChannel(item, url, streams), party.stream_idx || 0, 0)
      .then(() => setPartyViewerMode(true));
  }, { once: true });

  await connect(joinCode, false);
}

// ----------------------------------------------------------------- socket ---

async function connect(joinCode: string, isHost: boolean): Promise<void> {
  disconnect();
  currentCode = joinCode;

  const { data: u } = await getSupabase().auth.getUser();
  const profile = getActiveProfile();

  const base = WORKER_URL.replace(/^http/, "ws");
  const qs = new URLSearchParams({ party: joinCode, uid: u.user?.id || "", name: profile?.name || "Guest" });
  // The token is the ONLY thing that makes a connection the host's. A guest
  // never receives it, so a guest cannot send one.
  if (isHost) {
    const t = readHostToken(joinCode);
    if (t) qs.set("t", t);
  }
  socket = new WebSocket(`${base}?${qs.toString()}`);

  const emit = (detail: any, name: string) =>
    window.dispatchEvent(new CustomEvent(name, { detail }));

  socket.addEventListener("message", (e) => {
    let msg: any;
    try { msg = JSON.parse(String(e.data)); } catch { return; }
    switch (msg?.type) {
      case "state":
        if (!isHost) {
          lastHostState = msg.state as PartyPlaybackState;
          applyPartyState(lastHostState);
          showResync(false);
        }
        break;
      case "presence":
        peakViewers = Math.max(peakViewers, msg.viewers || 0);
        emit({ viewers: msg.viewers }, "veedeeoh:party-presence");
        break;
      case "roster":    emit({ watching: msg.watching, waiting: msg.waiting }, "veedeeoh:party-roster"); break;
      case "knock":     showToast(`${msg.name} wants to join`); break;
      case "pending":   emit({}, "veedeeoh:party-pending"); showToast("Waiting for the host to let you in"); break;
      case "admitted":  emit({}, "veedeeoh:party-admitted"); showToast("You're in"); break;
      case "start":     emit({}, "veedeeoh:party-start"); break;
      case "away":      if (!isHost) showHostAway(true); break;
      case "back":      if (!isHost) showHostAway(false); break;
      case "refused":   showToast("The host did not let you in"); break;
      case "removed":   showToast("The host removed you from the party"); disconnect(); break;
      case "closed": {
        // Was a toast and nothing else, so the film kept playing and a viewer
        // could not tell "the party ended" from "the host paused".
        const reason = msg.reason;
        forgetParty();
        disconnect();
        void import("./party-setup").then((m) => m.showPartyEnded({
          host: false,
          title: partyTitle || "the party",
          code: joinCode,
          watchedSecs: partyStartedAt ? (Date.now() - partyStartedAt) / 1000 : 0,
          reason,
        }));
        break;
      }
      case "removed":
        // Removed by the host: do not offer to walk back in.
        forgetParty();
        break;
    }
  });

  // A room the Durable Object has already closed 404s the upgrade, so the
  // socket never opens at all. Nothing distinguished that from a normal close,
  // so a guest sat in the green room waiting for a start signal that could
  // never arrive -- and the Supabase row still said the party was live, so the
  // next person walked into the same dead end.
  let everOpened = false;
  socket.addEventListener("open", () => { everOpened = true; });

  socket.addEventListener("close", (e) => {
    if (e.code === 1008 || e.code === 4009) { showToast("That party is full"); return; }
    if (e.code === 4003 || e.code === 4004) return;   // refused / removed, already reported

    if (!everOpened) {
      showToast("That party has ended");
      window.dispatchEvent(new CustomEvent("veedeeoh:party-dead"));
      forgetParty();
      // Close the row too, so nobody else follows the same link into a room
      // that no longer exists. Best effort: only the host may write it, and a
      // guest failing here is harmless.
      void getSupabase().from("parties")
        .update({ ended_at: new Date().toISOString() })
        .eq("join_code", joinCode)
        .then(() => {}, () => {});
      return;
    }

    // Opened and then dropped mid-party. For a guest that is usually the room
    // ending or the network going; either way say so rather than freezing.
    if (!isHost) showToast("Disconnected from the party");
  });

  if (isHost) {
    watchHostVisibility();
    setPartyEmitter((s) => {
      // Suppressed while the tab is hidden. A backgrounded browser pauses the
      // video, which would otherwise be emitted as paused:true and stop the
      // whole room -- turning "the host's phone rang" into "everyone's film
      // stopped". Absence is signalled once, as `away`, and viewers keep going.
      if (hostAway) return;
      if (socket?.readyState === WebSocket.OPEN) {
        // streamIdx travels; contentId does not. The episode index is what a
        // viewer needs to follow a binge, and it is meaningless outside this
        // party. contentId stays blank because every viewer already knows the
        // title and resolves their own URL for it -- sending the host's would
        // be a signed, per-session link that expires on them.
        socket.send(JSON.stringify({ type: "state", state: { ...s, contentId: "" } }));
      }
    });
  }
}

/** Host admits or refuses someone waiting in the lobby. */
export function respondToKnock(userId: string, admit: boolean): void {
  socket?.send(JSON.stringify({ type: admit ? "admit" : "refuse", userId }));
}

/** Host opens the doors. Until this is sent, every approved guest sits in the
 *  green room with a socket open and no playback state. */
export function startPlayback(): void {
  socket?.send(JSON.stringify({ type: "start" }));
}

/** Host removes someone already admitted. */
export function kickViewer(userId: string): void {
  socket?.send(JSON.stringify({ type: "kick", userId }));
}

/** Host ends the party for everyone, rather than leaving it to time out. */
export function endParty(): void {
  const secs = partyStartedAt ? (Date.now() - partyStartedAt) / 1000 : 0;
  const code = currentCode || "";
  const peak = peakViewers;
  const title = partyTitle;

  try { socket?.send(JSON.stringify({ type: "end" })); } catch {}
  disconnect();
  forgetParty();

  // The host was running something; tell them how it went rather than just
  // leaving the film playing as though nothing happened.
  void import("./party-setup").then((m) => m.showPartyEnded({
    host: true, title: title || "your party", code,
    watchedSecs: secs, peakViewers: peak, partyId: partyRowId,
  }));
}

export function disconnect(): void {
  stopMetering();
  partyStartedAt = 0;
  peakViewers = 0;
  stopPartySync();
  stopWatchingVisibility();
  showHostAway(false);
  showResync(false);
  setPartyViewerMode(false);
  lastHostState = null;
  setPartyEmitter(null);
  try { socket?.close(); } catch {}
  socket = null;
  currentCode = null;
}

export function activePartyCode(): string | null { return currentCode; }

/** Whether this deployment has a sync worker configured at all. */
export function partyEnabled(): boolean { return !!WORKER_URL; }

/** Start hosting for a title already open in the player. */
export async function hostExisting(joinCode: string): Promise<void> {
  await connect(joinCode, true);
  startMetering(joinCode);
}

// ---------------------------------------------------------------- metering ---
//
// Hosting is billed in 10-minute credits, wall clock. Metered from the client
// on an interval, which a modified client could dodge -- accepted deliberately,
// because hosting already requires an active subscription and credits are a
// premium quantity rather than a security control. The BALANCE itself is
// server-side: spend_party_credits is SECURITY DEFINER and no client can write
// profiles.party_credits directly.

let meterTimer: number | null = null;
// For the host's end-of-party summary. Tracked here because the party outlives
// any one player instance -- a host can close and reopen the video mid-party.
let partyStartedAt = 0;
let peakViewers = 0;
let partyTitle = "";
let partyRowId = "";
const METER_MINUTES = 10;

/** True if the account may start a party at all. Checked before the first
 *  credit is spent so a host with an empty balance is told up front rather than
 *  cut off ten minutes in. */
export async function hasHostingCredit(): Promise<{ ok: boolean; exempt: boolean; balance: number }> {
  const { ensurePartyCredits, partyCreditSummary } = await import("./db");
  // Grant this month's allowance first if it has not been issued yet, so a
  // comped account -- which never triggers an invoice -- is not told it is out
  // of hours it was never given.
  const c = (await ensurePartyCredits()) ?? (await partyCreditSummary());
  if (!c) return { ok: true, exempt: false, balance: 0 };   // no data: do not block
  return { ok: c.exempt || c.balance > 0, exempt: c.exempt, balance: c.balance };
}

function startMetering(joinCode: string): void {
  partyStartedAt = partyStartedAt || Date.now();
  stopMetering();
  void charge(joinCode);                                     // the first block is due now
  meterTimer = window.setInterval(() => void charge(joinCode), METER_MINUTES * 60_000);
}

function stopMetering(): void {
  if (meterTimer !== null) { clearInterval(meterTimer); meterTimer = null; }
}

async function charge(joinCode: string): Promise<void> {
  const { spendPartyCredits, partyCreditSummary } = await import("./db");
  const ok = await spendPartyCredits(METER_MINUTES, undefined);
  if (!ok) {
    // Out of credit. The party is NOT cut off: ending someone's film twenty
    // minutes from the finish is the most memorable possible bad experience,
    // and the marginal cost of letting it run is fractions of a cent.
    stopMetering();
    showToast("You're out of watch party hours. This party can finish.");
    window.dispatchEvent(new CustomEvent("veedeeoh:party-credits-out"));
    return;
  }
  const c = await partyCreditSummary();
  if (c && !c.exempt && c.balance === 1) {
    showToast("10 minutes of hosting left");
  }
}

// ------------------------------------------------------------------ lookup ---

async function lookupCatalogItem(contentId: string): Promise<any | null> {
  const { getVodRails } = await import("./vod");
  const rails = await getVodRails();
  for (const rail of rails) {
    for (const it of rail.items as any[]) if (String(it.id) === contentId) return it;
  }
  return null;
}

/** Mirrors asChannel in vod.ts so the player receives the shape it expects. */
function asPartyChannel(item: any, url: string | null, streams?: any[] | null): any {
  return {
    id: `vod:${item.id}`,
    name: item.title,
    country: null, categories: [], nsfw: false, logo: null, logos: [],
    streams: streams?.length ? streams : [{ url, quality: null, source: item.genre || "Party" }],
    source: item.genre || "Watch Party",
    vodPoster: item.poster, vodBanner: item.banner, vodItem: item,
  };
}


/** Full-screen "joining" cover. Returns its own dismiss function so every exit
 *  path from joinParty -- including the failures -- can drop it, rather than
 *  relying on one happy-path removal that a `return` above it would skip. */
function showJoining(code: string): () => void {
  const el = document.createElement("div");
  el.id = "partyJoining";
  el.innerHTML = `
    <div class="pjInner">
      <div class="pjMark">veedeeoh<span class="dot">.</span><span class="sfx">party</span></div>
      <div class="pjSub">Joining ${code.toUpperCase()}</div>
      <div class="vdTrackBar"><span></span></div>
    </div>`;
  document.body.appendChild(el);
  requestAnimationFrame(() => el.classList.add("in"));

  let gone = false;
  return () => {
    if (gone) return;
    gone = true;
    el.classList.remove("in");
    setTimeout(() => el.remove(), 380);
  };
}


// ------------------------------------------------------- viewer resync ---

let lastHostState: PartyPlaybackState | null = null;
let resyncEl: HTMLElement | null = null;

// A viewer whose browser refused to autoplay is stuck: the host is playing, the
// viewer is paused, and every heartbeat that follows is applied to a player
// that will not start. The only thing that can fix it is a real click, so ask
// for one.
if (typeof window !== "undefined") {
  window.addEventListener("veedeeoh:party-blocked", () => showResync(true, "Tap to join the party"));
}

function showResync(on: boolean, label = "Out of sync — resync"): void {
  if (!on) { resyncEl?.remove(); resyncEl = null; return; }
  if (resyncEl) return;

  resyncEl = document.createElement("button");
  resyncEl.id = "partyResync";
  resyncEl.textContent = label;
  resyncEl.addEventListener("click", () => {
    if (lastHostState) resyncToHost(lastHostState);
    showResync(false);
  });
  document.body.appendChild(resyncEl);
}


/** Walk a host back into a party they closed out of.
 *
 *  A host who shut the tab lost the room entirely: the token was per-tab, and
 *  nothing offered it back. The party itself was still alive -- the Durable
 *  Object only closes after five idle minutes -- so guests could still be
 *  sitting in it with nobody driving.
 */
export async function resumeHosting(joinCode: string): Promise<boolean> {
  if (!WORKER_URL) { showToast("Watch Party isn't configured yet"); return false; }
  if (!readHostToken(joinCode)) {
    forgetParty();
    showToast("That party can't be resumed from this device");
    return false;
  }

  const sb = getSupabase();
  // A host may still read their own rows directly under the new policy.
  const { data: party } = await sb.from("parties")
    .select("*").eq("join_code", joinCode).is("ended_at", null).maybeSingle();
  if (!party) { forgetParty(); showToast("That party has already ended"); return false; }

  const item = await lookupCatalogItem(party.content_id);
  if (!item) { showToast("That title isn't in the catalog any more"); return false; }

  const { resolveItemStream } = await import("./vod");
  const url = await resolveItemStream(item);
  if (!url) { showToast("That title can't be streamed right now"); return false; }

  await openVodPlayer(asPartyChannel(item, url, null), party.stream_idx || 0, 0);
  await hostExisting(joinCode);

  const { mountHostLobby } = await import("./party-setup");
  mountHostLobby(joinCode, partyLink(joinCode));
  // Already started, by definition -- the room existed before this. Re-announce
  // so anyone who joined while the host was away is let through rather than
  // left in a green room waiting on someone who has already begun.
  startPlayback();
  return true;
}


/** End a party the host is not currently connected to.
 *
 *  endParty() only works over a live socket. A host who closed the tab has no
 *  socket, so shutting the room down needs both halves: mark the row ended so
 *  nobody can look it up and join, and connect briefly to tell the Durable
 *  Object to disconnect whoever is still sitting in it. Without the second, the
 *  room stays open until the idle alarm fires five minutes later.
 */
export async function closeParty(joinCode: string): Promise<void> {
  try {
    await getSupabase().from("parties")
      .update({ ended_at: new Date().toISOString() })
      .eq("join_code", joinCode);
  } catch (e) { console.warn("[party] could not mark ended", e); }

  const token = readHostToken(joinCode);
  if (token && WORKER_URL) {
    try {
      await connect(joinCode, true);
      endParty();
    } catch { /* the row is already ended; the alarm will clear the object */ }
  }
  try { localStorage.removeItem(tokenKey(joinCode)); } catch {}
  forgetParty();
}


// ------------------------------------------------- host presence & absence ---

let hostAway = false;
let visHandler: (() => void) | null = null;

/** Tell viewers when the host's tab goes away, instead of letting a
 *  browser-forced pause propagate as a deliberate one.
 *
 *  This matters most on mobile, where iOS suspends timers and throttles sockets
 *  the moment the user switches apps or locks the screen -- a completely
 *  routine thing to do with a phone, and previously enough to stall a whole
 *  party on its last known position. */
function watchHostVisibility(): void {
  stopWatchingVisibility();
  visHandler = () => {
    const hidden = document.visibilityState === "hidden";
    if (hidden === hostAway) return;
    hostAway = hidden;
    try { socket?.send(JSON.stringify({ type: hidden ? "away" : "back" })); } catch {}
    // On return, resume if the browser paused us while backgrounded. Without
    // this the host comes back paused and the next heartbeat stops everyone --
    // reintroducing the exact problem one beat later.
    if (!hidden) {
      void import("./vodplayer").then((m) => m.resumeIfBackgroundPaused());
    }
  };
  document.addEventListener("visibilitychange", visHandler);
}

function stopWatchingVisibility(): void {
  if (visHandler) document.removeEventListener("visibilitychange", visHandler);
  visHandler = null;
  hostAway = false;
}

let awayEl: HTMLElement | null = null;

/** Viewer-side notice. Deliberately quiet and non-blocking: the film is still
 *  playing, and this is information, not an interruption. */
function showHostAway(on: boolean): void {
  if (!on) { awayEl?.remove(); awayEl = null; return; }
  if (awayEl) return;
  awayEl = document.createElement("div");
  awayEl.id = "partyHostAway";
  awayEl.textContent = "The host stepped away — still playing";
  document.body.appendChild(awayEl);
}


export interface PublicParty {
  join_code: string; title: string; content_id: string;
  host_user_id: string; seat_limit: number | null;
  started_at: string; joined_count: number;
  blurb: string | null; host_name: string | null;
  social_platform: string | null; social_handle: string | null;
}

/** Parties whose hosts chose to be listed. */
export async function listPublicParties(): Promise<PublicParty[]> {
  const { data, error } = await getSupabase().rpc("public_parties", { max_rows: 20 });
  if (error) { console.warn("[party] public list", error); return []; }
  return (data ?? []) as PublicParty[];
}


/** Whether this account may list another public party. Checked before the
 *  choice is offered rather than after it is made. */
export async function canListPublicParty(): Promise<{ ok: boolean; reason?: string }> {
  const { data, error } = await getSupabase().rpc("can_list_public_party");
  if (error) return { ok: true };   // guarded server-side regardless
  return (data as any) ?? { ok: true };
}

/** Signups attributable to one party -- what the host actually gets paid on,
 *  not a headcount of who turned up. */
export async function partySignups(partyId: string): Promise<number> {
  const { data, error } = await getSupabase().rpc("party_signups", { party: partyId });
  if (error) return 0;
  return Number(data) || 0;
}

/** Build a social URL from a platform and a handle. The handle is pattern
 *  checked in the database and the URL is assembled HERE, so no user-supplied
 *  link is ever rendered -- a disguised link or a redirect is not expressible. */
export function socialUrl(platform: string | null, handle: string | null): string | null {
  if (!platform || !handle) return null;
  const h = encodeURIComponent(handle);
  switch (platform) {
    case "discord":   return `https://discord.gg/${h}`;
    case "twitch":    return `https://twitch.tv/${h}`;
    case "youtube":   return `https://youtube.com/@${h}`;
    case "x":         return `https://x.com/${h}`;
    case "tiktok":    return `https://tiktok.com/@${h}`;
    case "instagram": return `https://instagram.com/${h}`;
    default:          return null;
  }
}
