// Watch Party client.
//
// Design: docs/plans/2026-08-21-watch-party-design.md
//
// The host is authoritative and viewers reconcile. Crucially, every viewer
// resolves its OWN signed stream URL rather than receiving the host's: Pluto
// JWTs are per-session and expire in 24h, so a shared URL would break for
// everyone at once. Only playback POSITION travels between peers.

import { getSupabase } from "./auth";
import { getActiveProfile } from "./profiles";
import { allowedRatingsFor } from "./db";
import { showToast } from "./util";
import { openVodPlayer, setPartyEmitter, applyPartyState, type PartyPlaybackState } from "./vodplayer";

const WORKER_URL = (import.meta.env.VITE_PARTY_WORKER_URL as string) || "";

let socket: WebSocket | null = null;
let currentCode: string | null = null;

function code6(): string {
  const A = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no O/0, I/1 — read aloud safely
  return Array.from({ length: 6 }, () => A[Math.floor(Math.random() * A.length)]).join("");
}

export function partyLink(joinCode: string): string {
  return `${location.origin}/index.html?party=${joinCode}`;
}

// ---------------------------------------------------------------- hosting ---

/** Hosting is an ACCOUNT-level entitlement: only the account owner starts a
 *  party, never a kids profile, and never a lapsed account.
 *
 *  The subscription check is the real anti-abuse control for the free tier. A
 *  lapsed guest may ATTEND a party, so they can only ever watch what a paying
 *  customer chose to play; letting them host would hand them the whole catalogue
 *  back and make the paywall decorative. Credits, when they arrive, are a
 *  quantity on top of this gate -- not a substitute for it.
 *
 *  Enforced again by RLS, because a hidden button is not a control.
 */
export async function canHost(): Promise<boolean> {
  if (getActiveProfile()?.is_kids) return false;
  const { data } = await getSupabase().auth.getUser();
  if (!data.user) return false;
  const { hasActiveAccess } = await import("./db");
  // Fail CLOSED here, unlike the browse gate. A transient error that wrongly
  // lets someone browse is a small mistake; one that lets a lapsed account host
  // is the hole this exists to close.
  try { return await hasActiveAccess(); } catch { return false; }
}

export interface PartyOptions {
  contentId: string;
  streamIdx: number;
  title: string;
  seatLimit?: number | null;
  requireApproval?: boolean;
}

/** 256 bits of randomness, generated by the host and never sent to a guest.
 *  This is what proves host identity to the Durable Object; the join code alone
 *  used to be enough, which meant anyone with the link could take the controls. */
function hostToken(): string {
  const b = new Uint8Array(32);
  crypto.getRandomValues(b);
  return Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");
}

const tokenKey = (joinCode: string) => `veedeeoh_party_host_${joinCode}`;

export async function createParty(opts: PartyOptions): Promise<{ joinCode: string; link: string }> {
  const { data: u } = await getSupabase().auth.getUser();
  if (!u.user) throw new Error("not signed in");
  if (!WORKER_URL) throw new Error("Watch Party isn't configured yet");

  const joinCode = code6();
  const token = hostToken();

  const { error } = await getSupabase().from("parties").insert({
    host_user_id: u.user.id,
    join_code: joinCode,
    content_id: opts.contentId,
    stream_idx: opts.streamIdx,
    title: opts.title,
    seat_limit: opts.seatLimit ?? null,
  });
  if (error) throw error;

  // Bind the party to this host BEFORE the link exists. Init is one-shot, so
  // there is no window in which someone who guessed the code could claim it.
  const res = await fetch(`${WORKER_URL}/init?party=${joinCode}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      hostToken: token,
      hostUserId: u.user.id,
      seatLimit: opts.seatLimit ?? null,
      requireApproval: opts.requireApproval !== false,
    }),
  });
  if (!res.ok) throw new Error("Couldn't start the party channel");

  // Kept locally so the host survives a reload without losing the controls.
  try { sessionStorage.setItem(tokenKey(joinCode), token); } catch {}

  return { joinCode, link: partyLink(joinCode) };
}

// ---------------------------------------------------------------- joining ---

export async function joinParty(joinCode: string): Promise<void> {
  if (!WORKER_URL) { showToast("Watch Party isn't configured yet"); return; }

  // A guest following a link previously landed on Home and waited through the
  // catalogue load, the party lookup and the stream resolve with nothing on
  // screen explaining any of it -- so the invite looked like it had failed
  // right up until the film appeared. Covered, and torn down on every exit
  // path below.
  const veil = showJoining(joinCode);

  const sb = getSupabase();
  const { data: party, error } = await sb.from("parties")
    .select("*").eq("join_code", joinCode).is("ended_at", null).maybeSingle();
  if (error || !party) { veil(); showToast("That party has ended or the link is wrong"); return; }

  // THE KIDS TRAP. A party link handed to a kids profile would otherwise play
  // whatever the host is playing. Refuse outright rather than filtering -- a
  // control any Discord link walks around is not a control.
  const profile = getActiveProfile();
  const allowed = allowedRatingsFor(profile);
  if (allowed) {
    const item = await lookupCatalogItem(party.content_id);
    const rating = (item?.rating || "").toUpperCase();
    if (!rating || !allowed.has(rating)) {
      veil();
      showToast(`This party is playing something outside ${profile.name}'s rating limits`);
      return;
    }
  }

  const { data: u } = await sb.auth.getUser();
  if (!u.user) { veil(); showToast("Sign in to join the party"); return; }

  // Two separate records, deliberately. party_joins is the presence log for
  // this party; the referral is a permanent, first-touch claim on the guest's
  // account that outlives it. attribute_party_join is a no-op if the guest
  // already has a referrer, so an existing customer joining a party does not
  // get reassigned to the host.
  await sb.from("party_joins").upsert({
    party_id: party.id, user_id: u.user.id, host_user_id: party.host_user_id,
  }).then(({ error: e }) => { if (e) console.warn("[party] join not recorded", e); });

  await sb.rpc("attribute_party_join", { party: party.id })
    .then(({ error: e }) => { if (e) console.warn("[party] referral not recorded", e); });

  const item = await lookupCatalogItem(party.content_id);
  if (!item) { veil(); showToast("That title isn't in the catalog any more"); return; }

  // Each viewer resolves their OWN url -- a Pluto JWT is per-session and
  // expires, so the host's cannot be shared. asPartyChannel used to read
  // `item.url`, which is only set for legacy catalogue rows, so a Pluto, Tubi
  // or Archive title handed the player a stream with url undefined and the
  // joiner landed on "this title isn't available to stream right now".
  const { resolveItemStream } = await import("./vod");
  const url = await resolveItemStream(item);
  if (!url) { veil(); showToast("That title can't be streamed right now"); return; }

  await openVodPlayer(asPartyChannel(item, url), party.stream_idx || 0, 0);
  await connect(joinCode, false);
  veil();
}

// ----------------------------------------------------------------- socket ---

async function connect(joinCode: string, isHost: boolean): Promise<void> {
  disconnect();
  currentCode = joinCode;

  const { data: u } = await getSupabase().auth.getUser();
  const profile = getActiveProfile();

  const base = WORKER_URL.replace(/^http/, "ws");
  const qs = new URLSearchParams({ party: joinCode, uid: u.user?.id || "", name: profile?.name || "Guest" });
  // The token is the ONLY thing that makes a connection the host's. A guest
  // never receives it, so a guest cannot send one.
  if (isHost) {
    const t = sessionStorage.getItem(tokenKey(joinCode));
    if (t) qs.set("t", t);
  }
  socket = new WebSocket(`${base}?${qs.toString()}`);

  const emit = (detail: any, name: string) =>
    window.dispatchEvent(new CustomEvent(name, { detail }));

  socket.addEventListener("message", (e) => {
    let msg: any;
    try { msg = JSON.parse(String(e.data)); } catch { return; }
    switch (msg?.type) {
      case "state":     if (!isHost) applyPartyState(msg.state as PartyPlaybackState); break;
      case "presence":  emit({ viewers: msg.viewers }, "veedeeoh:party-presence"); break;
      case "waiting":   emit({ waiting: msg.waiting }, "veedeeoh:party-waiting"); break;
      case "knock":     showToast(`${msg.name} wants to join`); break;
      case "pending":   emit({}, "veedeeoh:party-pending"); showToast("Waiting for the host to let you in"); break;
      case "admitted":  emit({}, "veedeeoh:party-admitted"); showToast("You're in"); break;
      case "refused":   showToast("The host did not let you in"); break;
      case "closed":    showToast(msg.reason === "idle" ? "The party timed out" : "The host ended the party"); disconnect(); break;
    }
  });

  socket.addEventListener("close", (e) => {
    if (e.code === 1008 || e.code === 4009) showToast("That party is full");
  });

  if (isHost) {
    setPartyEmitter((s) => {
      if (socket?.readyState === WebSocket.OPEN) {
        socket.send(JSON.stringify({ type: "state", state: { ...s, contentId: "", streamIdx: 0 } }));
      }
    });
  }
}

/** Host admits or refuses someone waiting in the lobby. */
export function respondToKnock(userId: string, admit: boolean): void {
  socket?.send(JSON.stringify({ type: admit ? "admit" : "refuse", userId }));
}

/** Host ends the party for everyone, rather than leaving it to time out. */
export function endParty(): void {
  try { socket?.send(JSON.stringify({ type: "end" })); } catch {}
  disconnect();
}

export function disconnect(): void {
  stopMetering();
  setPartyEmitter(null);
  try { socket?.close(); } catch {}
  socket = null;
  currentCode = null;
}

export function activePartyCode(): string | null { return currentCode; }

/** Whether this deployment has a sync worker configured at all. */
export function partyEnabled(): boolean { return !!WORKER_URL; }

/** Start hosting for a title already open in the player. */
export async function hostExisting(joinCode: string): Promise<void> {
  await connect(joinCode, true);
  startMetering(joinCode);
}

// ---------------------------------------------------------------- metering ---
//
// Hosting is billed in 10-minute credits, wall clock. Metered from the client
// on an interval, which a modified client could dodge -- accepted deliberately,
// because hosting already requires an active subscription and credits are a
// premium quantity rather than a security control. The BALANCE itself is
// server-side: spend_party_credits is SECURITY DEFINER and no client can write
// profiles.party_credits directly.

let meterTimer: number | null = null;
const METER_MINUTES = 10;

/** True if the account may start a party at all. Checked before the first
 *  credit is spent so a host with an empty balance is told up front rather than
 *  cut off ten minutes in. */
export async function hasHostingCredit(): Promise<{ ok: boolean; exempt: boolean; balance: number }> {
  const { ensurePartyCredits, partyCreditSummary } = await import("./db");
  // Grant this month's allowance first if it has not been issued yet, so a
  // comped account -- which never triggers an invoice -- is not told it is out
  // of hours it was never given.
  const c = (await ensurePartyCredits()) ?? (await partyCreditSummary());
  if (!c) return { ok: true, exempt: false, balance: 0 };   // no data: do not block
  return { ok: c.exempt || c.balance > 0, exempt: c.exempt, balance: c.balance };
}

function startMetering(joinCode: string): void {
  stopMetering();
  void charge(joinCode);                                     // the first block is due now
  meterTimer = window.setInterval(() => void charge(joinCode), METER_MINUTES * 60_000);
}

function stopMetering(): void {
  if (meterTimer !== null) { clearInterval(meterTimer); meterTimer = null; }
}

async function charge(joinCode: string): Promise<void> {
  const { spendPartyCredits, partyCreditSummary } = await import("./db");
  const ok = await spendPartyCredits(METER_MINUTES, undefined);
  if (!ok) {
    // Out of credit. The party is NOT cut off: ending someone's film twenty
    // minutes from the finish is the most memorable possible bad experience,
    // and the marginal cost of letting it run is fractions of a cent.
    stopMetering();
    showToast("You're out of watch party hours. This party can finish.");
    window.dispatchEvent(new CustomEvent("veedeeoh:party-credits-out"));
    return;
  }
  const c = await partyCreditSummary();
  if (c && !c.exempt && c.balance === 1) {
    showToast("10 minutes of hosting left");
  }
}

// ------------------------------------------------------------------ lookup ---

async function lookupCatalogItem(contentId: string): Promise<any | null> {
  const { getVodRails } = await import("./vod");
  const rails = await getVodRails();
  for (const rail of rails) {
    for (const it of rail.items as any[]) if (String(it.id) === contentId) return it;
  }
  return null;
}

/** Mirrors asChannel in vod.ts so the player receives the shape it expects. */
function asPartyChannel(item: any, url: string): any {
  return {
    id: `vod:${item.id}`,
    name: item.title,
    country: null, categories: [], nsfw: false, logo: null, logos: [],
    streams: [{ url, quality: null, source: item.genre || "Party" }],
    source: item.genre || "Watch Party",
    vodPoster: item.poster, vodBanner: item.banner, vodItem: item,
  };
}


/** Full-screen "joining" cover. Returns its own dismiss function so every exit
 *  path from joinParty -- including the failures -- can drop it, rather than
 *  relying on one happy-path removal that a `return` above it would skip. */
function showJoining(code: string): () => void {
  const el = document.createElement("div");
  el.id = "partyJoining";
  el.innerHTML = `
    <div class="pjInner">
      <div class="pjMark">veedeeoh<span class="dot">.</span><span class="sfx">party</span></div>
      <div class="pjSub">Joining ${code.toUpperCase()}</div>
      <div class="vdTrackBar"><span></span></div>
    </div>`;
  document.body.appendChild(el);
  requestAnimationFrame(() => el.classList.add("in"));

  let gone = false;
  return () => {
    if (gone) return;
    gone = true;
    el.classList.remove("in");
    setTimeout(() => el.remove(), 380);
  };
}
